// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: keystore_api/v1/keystore.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.keystore_api.v1;

@kotlin.jvm.JvmName("-initializedecryptV1Request")
public inline fun decryptV1Request(block: com.xmtp.keystore_api.v1.DecryptV1RequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.DecryptV1Request =
  com.xmtp.keystore_api.v1.DecryptV1RequestKt.Dsl._create(com.xmtp.keystore_api.v1.DecryptV1Request.newBuilder()).apply { block() }._build()
/**
 * ```
 * Decrypt a batch of messages using X3DH key agreement
 * ```
 *
 * Protobuf type `xmtp.keystore_api.v1.DecryptV1Request`
 */
public object DecryptV1RequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.keystore_api.v1.DecryptV1Request.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.keystore_api.v1.DecryptV1Request.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.keystore_api.v1.DecryptV1Request = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RequestsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     */
     public val requests: com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRequestsList()
      )
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     * @param value The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>.add(value: com.xmtp.keystore_api.v1.DecryptV1Request.Request) {
      _builder.addRequests(value)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     * @param value The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRequests")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>.plusAssign(value: com.xmtp.keystore_api.v1.DecryptV1Request.Request) {
      add(value)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     * @param values The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>.addAll(values: kotlin.collections.Iterable<com.xmtp.keystore_api.v1.DecryptV1Request.Request>) {
      _builder.addAllRequests(values)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     * @param values The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRequests")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>.plusAssign(values: kotlin.collections.Iterable<com.xmtp.keystore_api.v1.DecryptV1Request.Request>) {
      addAll(values)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     * @param index The index to set the value at.
     * @param value The requests to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRequests")
    public operator fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>.set(index: kotlin.Int, value: com.xmtp.keystore_api.v1.DecryptV1Request.Request) {
      _builder.setRequests(index, value)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.DecryptV1Request.Request requests = 1 [json_name = "requests"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.DecryptV1Request.Request, RequestsProxy>.clear() {
      _builder.clearRequests()
    }

  }
  @kotlin.jvm.JvmName("-initializerequest")
  public inline fun request(block: com.xmtp.keystore_api.v1.DecryptV1RequestKt.RequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.DecryptV1Request.Request =
    com.xmtp.keystore_api.v1.DecryptV1RequestKt.RequestKt.Dsl._create(com.xmtp.keystore_api.v1.DecryptV1Request.Request.newBuilder()).apply { block() }._build()
  /**
   * ```
   * A single decryption request
   * ```
   *
   * Protobuf type `xmtp.keystore_api.v1.DecryptV1Request.Request`
   */
  public object RequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.xmtp.keystore_api.v1.DecryptV1Request.Request.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.xmtp.keystore_api.v1.DecryptV1Request.Request.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.xmtp.keystore_api.v1.DecryptV1Request.Request = _builder.build()

      /**
       * `.xmtp.message_contents.Ciphertext payload = 1 [json_name = "payload"];`
       */
      public var payload: com.xmtp.message_contents.Ciphertext
        @JvmName("getPayload")
        get() = _builder.getPayload()
        @JvmName("setPayload")
        set(value) {
          _builder.setPayload(value)
        }
      /**
       * `.xmtp.message_contents.Ciphertext payload = 1 [json_name = "payload"];`
       */
      public fun clearPayload() {
        _builder.clearPayload()
      }
      /**
       * `.xmtp.message_contents.Ciphertext payload = 1 [json_name = "payload"];`
       * @return Whether the payload field is set.
       */
      public fun hasPayload(): kotlin.Boolean {
        return _builder.hasPayload()
      }

      /**
       * `.xmtp.message_contents.PublicKeyBundle peer_keys = 2 [json_name = "peerKeys"];`
       */
      public var peerKeys: com.xmtp.message_contents.PublicKeyBundle
        @JvmName("getPeerKeys")
        get() = _builder.getPeerKeys()
        @JvmName("setPeerKeys")
        set(value) {
          _builder.setPeerKeys(value)
        }
      /**
       * `.xmtp.message_contents.PublicKeyBundle peer_keys = 2 [json_name = "peerKeys"];`
       */
      public fun clearPeerKeys() {
        _builder.clearPeerKeys()
      }
      /**
       * `.xmtp.message_contents.PublicKeyBundle peer_keys = 2 [json_name = "peerKeys"];`
       * @return Whether the peerKeys field is set.
       */
      public fun hasPeerKeys(): kotlin.Boolean {
        return _builder.hasPeerKeys()
      }

      /**
       * `bytes header_bytes = 3 [json_name = "headerBytes"];`
       */
      public var headerBytes: com.google.protobuf.ByteString
        @JvmName("getHeaderBytes")
        get() = _builder.getHeaderBytes()
        @JvmName("setHeaderBytes")
        set(value) {
          _builder.setHeaderBytes(value)
        }
      /**
       * `bytes header_bytes = 3 [json_name = "headerBytes"];`
       */
      public fun clearHeaderBytes() {
        _builder.clearHeaderBytes()
      }

      /**
       * `bool is_sender = 4 [json_name = "isSender"];`
       */
      public var isSender: kotlin.Boolean
        @JvmName("getIsSender")
        get() = _builder.getIsSender()
        @JvmName("setIsSender")
        set(value) {
          _builder.setIsSender(value)
        }
      /**
       * `bool is_sender = 4 [json_name = "isSender"];`
       */
      public fun clearIsSender() {
        _builder.clearIsSender()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.keystore_api.v1.DecryptV1Request.copy(block: com.xmtp.keystore_api.v1.DecryptV1RequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.DecryptV1Request =
  com.xmtp.keystore_api.v1.DecryptV1RequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.keystore_api.v1.DecryptV1Request.Request.copy(block: com.xmtp.keystore_api.v1.DecryptV1RequestKt.RequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.DecryptV1Request.Request =
  com.xmtp.keystore_api.v1.DecryptV1RequestKt.RequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.keystore_api.v1.DecryptV1Request.RequestOrBuilder.payloadOrNull: com.xmtp.message_contents.Ciphertext?
  get() = if (hasPayload()) getPayload() else null

public val com.xmtp.keystore_api.v1.DecryptV1Request.RequestOrBuilder.peerKeysOrNull: com.xmtp.message_contents.PublicKeyBundle?
  get() = if (hasPeerKeys()) getPeerKeys() else null

