// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: keystore_api/v1/keystore.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.keystore_api.v1;

@kotlin.jvm.JvmName("-initializesaveInvitesRequest")
public inline fun saveInvitesRequest(block: com.xmtp.keystore_api.v1.SaveInvitesRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.SaveInvitesRequest =
  com.xmtp.keystore_api.v1.SaveInvitesRequestKt.Dsl._create(com.xmtp.keystore_api.v1.SaveInvitesRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Request to save a batch of invite messages to the Keystore
 * ```
 *
 * Protobuf type `xmtp.keystore_api.v1.SaveInvitesRequest`
 */
public object SaveInvitesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.keystore_api.v1.SaveInvitesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.keystore_api.v1.SaveInvitesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.keystore_api.v1.SaveInvitesRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RequestsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     */
     public val requests: com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRequestsList()
      )
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     * @param value The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>.add(value: com.xmtp.keystore_api.v1.SaveInvitesRequest.Request) {
      _builder.addRequests(value)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     * @param value The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRequests")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>.plusAssign(value: com.xmtp.keystore_api.v1.SaveInvitesRequest.Request) {
      add(value)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     * @param values The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>.addAll(values: kotlin.collections.Iterable<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request>) {
      _builder.addAllRequests(values)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     * @param values The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRequests")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>.plusAssign(values: kotlin.collections.Iterable<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request>) {
      addAll(values)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     * @param index The index to set the value at.
     * @param value The requests to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRequests")
    public operator fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>.set(index: kotlin.Int, value: com.xmtp.keystore_api.v1.SaveInvitesRequest.Request) {
      _builder.setRequests(index, value)
    }
    /**
     * `repeated .xmtp.keystore_api.v1.SaveInvitesRequest.Request requests = 1 [json_name = "requests"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.keystore_api.v1.SaveInvitesRequest.Request, RequestsProxy>.clear() {
      _builder.clearRequests()
    }
  }
  @kotlin.jvm.JvmName("-initializerequest")
  public inline fun request(block: com.xmtp.keystore_api.v1.SaveInvitesRequestKt.RequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.SaveInvitesRequest.Request =
    com.xmtp.keystore_api.v1.SaveInvitesRequestKt.RequestKt.Dsl._create(com.xmtp.keystore_api.v1.SaveInvitesRequest.Request.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Mirrors xmtp.envelope schema
   * ```
   *
   * Protobuf type `xmtp.keystore_api.v1.SaveInvitesRequest.Request`
   */
  public object RequestKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.xmtp.keystore_api.v1.SaveInvitesRequest.Request.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.xmtp.keystore_api.v1.SaveInvitesRequest.Request.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.xmtp.keystore_api.v1.SaveInvitesRequest.Request = _builder.build()

      /**
       * `string content_topic = 1 [json_name = "contentTopic"];`
       */
      public var contentTopic: kotlin.String
        @JvmName("getContentTopic")
        get() = _builder.getContentTopic()
        @JvmName("setContentTopic")
        set(value) {
          _builder.setContentTopic(value)
        }
      /**
       * `string content_topic = 1 [json_name = "contentTopic"];`
       */
      public fun clearContentTopic() {
        _builder.clearContentTopic()
      }

      /**
       * <code>uint64 timestamp_ns = 2 [json_name = "timestampNs"];</code>
       */
      public var timestampNs: kotlin.Long
        @JvmName("getTimestampNs")
        get() = _builder.getTimestampNs()
        @JvmName("setTimestampNs")
        set(value) {
          _builder.setTimestampNs(value)
        }
      /**
       * `uint64 timestamp_ns = 2 [json_name = "timestampNs"];`
       */
      public fun clearTimestampNs() {
        _builder.clearTimestampNs()
      }

      /**
       * <code>bytes payload = 3 [json_name = "payload"];</code>
       */
      public var payload: com.google.protobuf.ByteString
        @JvmName("getPayload")
        get() = _builder.getPayload()
        @JvmName("setPayload")
        set(value) {
          _builder.setPayload(value)
        }
      /**
       * `bytes payload = 3 [json_name = "payload"];`
       */
      public fun clearPayload() {
        _builder.clearPayload()
      }
    }
  }
}
public inline fun com.xmtp.keystore_api.v1.SaveInvitesRequest.copy(block: com.xmtp.keystore_api.v1.SaveInvitesRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.SaveInvitesRequest =
  com.xmtp.keystore_api.v1.SaveInvitesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.xmtp.keystore_api.v1.SaveInvitesRequest.Request.copy(block: com.xmtp.keystore_api.v1.SaveInvitesRequestKt.RequestKt.Dsl.() -> kotlin.Unit): com.xmtp.keystore_api.v1.SaveInvitesRequest.Request =
  com.xmtp.keystore_api.v1.SaveInvitesRequestKt.RequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

