// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/contact.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

