// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/contact.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializecontactBundleV1")
public inline fun contactBundleV1(block: com.xmtp.message_contents.ContactBundleV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.ContactBundleV1 =
  com.xmtp.message_contents.ContactBundleV1Kt.Dsl._create(com.xmtp.message_contents.ContactBundleV1.newBuilder()).apply { block() }._build()
/**
 * ```
 * LEGACY: User key bundle V1 using PublicKeys.
 * The PublicKeys MUST be signed.
 * ```
 *
 * Protobuf type `xmtp.message_contents.ContactBundleV1`
 */
public object ContactBundleV1Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.ContactBundleV1.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.ContactBundleV1.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.ContactBundleV1 = _builder.build()

    /**
     * `.xmtp.message_contents.PublicKeyBundle key_bundle = 1 [json_name = "keyBundle"];`
     */
    public var keyBundle: com.xmtp.message_contents.PublicKeyBundle
      @JvmName("getKeyBundle")
      get() = _builder.getKeyBundle()
      @JvmName("setKeyBundle")
      set(value) {
        _builder.setKeyBundle(value)
      }
    /**
     * `.xmtp.message_contents.PublicKeyBundle key_bundle = 1 [json_name = "keyBundle"];`
     */
    public fun clearKeyBundle() {
      _builder.clearKeyBundle()
    }
    /**
     * `.xmtp.message_contents.PublicKeyBundle key_bundle = 1 [json_name = "keyBundle"];`
     * @return Whether the keyBundle field is set.
     */
    public fun hasKeyBundle(): kotlin.Boolean {
      return _builder.hasKeyBundle()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.ContactBundleV1.copy(block: com.xmtp.message_contents.ContactBundleV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.ContactBundleV1 =
  com.xmtp.message_contents.ContactBundleV1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.ContactBundleV1OrBuilder.keyBundleOrNull: com.xmtp.message_contents.PublicKeyBundle?
  get() = if (hasKeyBundle()) getKeyBundle() else null

