// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/private_key.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializeencryptedPrivateKeyBundleV1")
public inline fun encryptedPrivateKeyBundleV1(block: com.xmtp.message_contents.EncryptedPrivateKeyBundleV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.EncryptedPrivateKeyBundleV1 =
  com.xmtp.message_contents.EncryptedPrivateKeyBundleV1Kt.Dsl._create(com.xmtp.message_contents.EncryptedPrivateKeyBundleV1.newBuilder()).apply { block() }._build()
/**
 * ```
 * PrivateKeyBundle encrypted with key material generated by
 * signing a randomly generated "pre-key" with the user's wallet,
 * i.e. EIP-191 signature of a "storage signature" message with
 * the pre-key embedded in it.
 * (see xmtp-js::PrivateKeyBundle.toEncryptedBytes for details)
 * ```
 *
 * Protobuf type `xmtp.message_contents.EncryptedPrivateKeyBundleV1`
 */
public object EncryptedPrivateKeyBundleV1Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.EncryptedPrivateKeyBundleV1.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.EncryptedPrivateKeyBundleV1.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.EncryptedPrivateKeyBundleV1 = _builder.build()

    /**
     * ```
     * randomly generated pre-key 
     * ```
     *
     * `bytes wallet_pre_key = 1 [json_name = "walletPreKey"];`
     */
    public var walletPreKey: com.google.protobuf.ByteString
      @JvmName("getWalletPreKey")
      get() = _builder.getWalletPreKey()
      @JvmName("setWalletPreKey")
      set(value) {
        _builder.setWalletPreKey(value)
      }
    /**
     * ```
     * randomly generated pre-key 
     * ```
     *
     * `bytes wallet_pre_key = 1 [json_name = "walletPreKey"];`
     */
    public fun clearWalletPreKey() {
      _builder.clearWalletPreKey()
    }

    /**
     * ```
     * MUST contain encrypted PrivateKeyBundle
     * ```
     *
     * `.xmtp.message_contents.Ciphertext ciphertext = 2 [json_name = "ciphertext"];`
     */
    public var ciphertext: com.xmtp.message_contents.Ciphertext
      @JvmName("getCiphertext")
      get() = _builder.getCiphertext()
      @JvmName("setCiphertext")
      set(value) {
        _builder.setCiphertext(value)
      }
    /**
     * ```
     * MUST contain encrypted PrivateKeyBundle
     * ```
     *
     * `.xmtp.message_contents.Ciphertext ciphertext = 2 [json_name = "ciphertext"];`
     */
    public fun clearCiphertext() {
      _builder.clearCiphertext()
    }
    /**
     * ```
     * MUST contain encrypted PrivateKeyBundle
     * ```
     *
     * `.xmtp.message_contents.Ciphertext ciphertext = 2 [json_name = "ciphertext"];`
     * @return Whether the ciphertext field is set.
     */
    public fun hasCiphertext(): kotlin.Boolean {
      return _builder.hasCiphertext()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.EncryptedPrivateKeyBundleV1.copy(block: com.xmtp.message_contents.EncryptedPrivateKeyBundleV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.EncryptedPrivateKeyBundleV1 =
  com.xmtp.message_contents.EncryptedPrivateKeyBundleV1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.EncryptedPrivateKeyBundleV1OrBuilder.ciphertextOrNull: com.xmtp.message_contents.Ciphertext?
  get() = if (hasCiphertext()) getCiphertext() else null

