// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/private_key.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializeencryptedPrivateKeyBundle")
public inline fun encryptedPrivateKeyBundle(block: com.xmtp.message_contents.EncryptedPrivateKeyBundleKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.EncryptedPrivateKeyBundle =
  com.xmtp.message_contents.EncryptedPrivateKeyBundleKt.Dsl._create(com.xmtp.message_contents.EncryptedPrivateKeyBundle.newBuilder()).apply { block() }._build()
/**
 * ```
 * Versioned encrypted PrivateKeyBundle
 * ```
 *
 * Protobuf type `xmtp.message_contents.EncryptedPrivateKeyBundle`
 */
public object EncryptedPrivateKeyBundleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.EncryptedPrivateKeyBundle.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.EncryptedPrivateKeyBundle.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.EncryptedPrivateKeyBundle = _builder.build()

    /**
     * `.xmtp.message_contents.EncryptedPrivateKeyBundleV1 v1 = 1 [json_name = "v1"];`
     */
    public var v1: com.xmtp.message_contents.EncryptedPrivateKeyBundleV1
      @JvmName("getV1")
      get() = _builder.getV1()
      @JvmName("setV1")
      set(value) {
        _builder.setV1(value)
      }
    /**
     * `.xmtp.message_contents.EncryptedPrivateKeyBundleV1 v1 = 1 [json_name = "v1"];`
     */
    public fun clearV1() {
      _builder.clearV1()
    }
    /**
     * `.xmtp.message_contents.EncryptedPrivateKeyBundleV1 v1 = 1 [json_name = "v1"];`
     * @return Whether the v1 field is set.
     */
    public fun hasV1(): kotlin.Boolean {
      return _builder.hasV1()
    }
    public val versionCase: com.xmtp.message_contents.EncryptedPrivateKeyBundle.VersionCase
      @JvmName("getVersionCase")
      get() = _builder.getVersionCase()

    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
public inline fun com.xmtp.message_contents.EncryptedPrivateKeyBundle.copy(block: com.xmtp.message_contents.EncryptedPrivateKeyBundleKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.EncryptedPrivateKeyBundle =
  com.xmtp.message_contents.EncryptedPrivateKeyBundleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.EncryptedPrivateKeyBundleOrBuilder.v1OrNull: com.xmtp.message_contents.EncryptedPrivateKeyBundleV1?
  get() = if (hasV1()) getV1() else null

