// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/invitation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializeinvitationV1")
public inline fun invitationV1(block: com.xmtp.message_contents.InvitationV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.InvitationV1 =
  com.xmtp.message_contents.InvitationV1Kt.Dsl._create(com.xmtp.message_contents.InvitationV1.newBuilder()).apply { block() }._build()
/**
 * ```
 * Unsealed invitation V1
 * ```
 *
 * Protobuf type `xmtp.message_contents.InvitationV1`
 */
public object InvitationV1Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.InvitationV1.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.InvitationV1.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.InvitationV1 = _builder.build()

    /**
     * ```
     * topic name chosen for this conversation.
     * It MUST be randomly generated bytes (length >= 32),
     * then base64 encoded without padding
     * ```
     *
     * `string topic = 1 [json_name = "topic"];`
     */
    public var topic: kotlin.String
      @JvmName("getTopic")
      get() = _builder.getTopic()
      @JvmName("setTopic")
      set(value) {
        _builder.setTopic(value)
      }
    /**
     * ```
     * topic name chosen for this conversation.
     * It MUST be randomly generated bytes (length >= 32),
     * then base64 encoded without padding
     * ```
     *
     * `string topic = 1 [json_name = "topic"];`
     */
    public fun clearTopic() {
      _builder.clearTopic()
    }

    /**
     * ```
     * A context object defining metadata
     * ```
     *
     * `.xmtp.message_contents.InvitationV1.Context context = 2 [json_name = "context"];`
     */
    public var context: com.xmtp.message_contents.InvitationV1.Context
      @JvmName("getContext")
      get() = _builder.getContext()
      @JvmName("setContext")
      set(value) {
        _builder.setContext(value)
      }
    /**
     * ```
     * A context object defining metadata
     * ```
     *
     * `.xmtp.message_contents.InvitationV1.Context context = 2 [json_name = "context"];`
     */
    public fun clearContext() {
      _builder.clearContext()
    }
    /**
     * ```
     * A context object defining metadata
     * ```
     *
     * `.xmtp.message_contents.InvitationV1.Context context = 2 [json_name = "context"];`
     * @return Whether the context field is set.
     */
    public fun hasContext(): kotlin.Boolean {
      return _builder.hasContext()
    }

    /**
     * ```
     * Specify the encryption method to process the key material properly.
     * ```
     *
     * `.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256 aes256_gcm_hkdf_sha256 = 3 [json_name = "aes256GcmHkdfSha256"];`
     */
    public var aes256GcmHkdfSha256: com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256
      @JvmName("getAes256GcmHkdfSha256")
      get() = _builder.getAes256GcmHkdfSha256()
      @JvmName("setAes256GcmHkdfSha256")
      set(value) {
        _builder.setAes256GcmHkdfSha256(value)
      }
    /**
     * ```
     * Specify the encryption method to process the key material properly.
     * ```
     *
     * `.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256 aes256_gcm_hkdf_sha256 = 3 [json_name = "aes256GcmHkdfSha256"];`
     */
    public fun clearAes256GcmHkdfSha256() {
      _builder.clearAes256GcmHkdfSha256()
    }
    /**
     * ```
     * Specify the encryption method to process the key material properly.
     * ```
     *
     * `.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256 aes256_gcm_hkdf_sha256 = 3 [json_name = "aes256GcmHkdfSha256"];`
     * @return Whether the aes256GcmHkdfSha256 field is set.
     */
    public fun hasAes256GcmHkdfSha256(): kotlin.Boolean {
      return _builder.hasAes256GcmHkdfSha256()
    }
    public val encryptionCase: com.xmtp.message_contents.InvitationV1.EncryptionCase
      @JvmName("getEncryptionCase")
      get() = _builder.getEncryptionCase()

    public fun clearEncryption() {
      _builder.clearEncryption()
    }
  }
  @kotlin.jvm.JvmName("-initializeaes256gcmHkdfsha256")
  public inline fun aes256gcmHkdfsha256(block: com.xmtp.message_contents.InvitationV1Kt.Aes256gcmHkdfsha256Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256 =
    com.xmtp.message_contents.InvitationV1Kt.Aes256gcmHkdfsha256Kt.Dsl._create(com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Supported encryption schemes
   * AES256-GCM-HKDF-SHA256
   * ```
   *
   * Protobuf type `xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256`
   */
  public object Aes256gcmHkdfsha256Kt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256 = _builder.build()

      /**
       * ```
       * randomly generated key material (32 bytes)
       * ```
       *
       * `bytes key_material = 1 [json_name = "keyMaterial"];`
       */
      public var keyMaterial: com.google.protobuf.ByteString
        @JvmName("getKeyMaterial")
        get() = _builder.getKeyMaterial()
        @JvmName("setKeyMaterial")
        set(value) {
          _builder.setKeyMaterial(value)
        }
      /**
       * ```
       * randomly generated key material (32 bytes)
       * ```
       *
       * `bytes key_material = 1 [json_name = "keyMaterial"];`
       */
      public fun clearKeyMaterial() {
        _builder.clearKeyMaterial()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializecontext")
  public inline fun context(block: com.xmtp.message_contents.InvitationV1Kt.ContextKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.InvitationV1.Context =
    com.xmtp.message_contents.InvitationV1Kt.ContextKt.Dsl._create(com.xmtp.message_contents.InvitationV1.Context.newBuilder()).apply { block() }._build()
  /**
   * ```
   * The context type
   * ```
   *
   * Protobuf type `xmtp.message_contents.InvitationV1.Context`
   */
  public object ContextKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.xmtp.message_contents.InvitationV1.Context.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.xmtp.message_contents.InvitationV1.Context.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.xmtp.message_contents.InvitationV1.Context = _builder.build()

      /**
       * ```
       * Expected to be a URI (ie xmtp.org/convo1)
       * ```
       *
       * `string conversation_id = 1 [json_name = "conversationId"];`
       */
      public var conversationId: kotlin.String
        @JvmName("getConversationId")
        get() = _builder.getConversationId()
        @JvmName("setConversationId")
        set(value) {
          _builder.setConversationId(value)
        }
      /**
       * ```
       * Expected to be a URI (ie xmtp.org/convo1)
       * ```
       *
       * `string conversation_id = 1 [json_name = "conversationId"];`
       */
      public fun clearConversationId() {
        _builder.clearConversationId()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class MetadataProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * Key value map of additional metadata that would be exposed to
       * application developers and could be used for filtering
       * ```
       *
       * `map<string, string> metadata = 2 [json_name = "metadata"];`
       */
       public val metadata: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
        @kotlin.jvm.JvmSynthetic
        @JvmName("getMetadataMap")
        get() = com.google.protobuf.kotlin.DslMap(
          _builder.getMetadataMap()
        )
      /**
       * ```
       * Key value map of additional metadata that would be exposed to
       * application developers and could be used for filtering
       * ```
       *
       * `map<string, string> metadata = 2 [json_name = "metadata"];`
       */
      @JvmName("putMetadata")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
        .put(key: kotlin.String, value: kotlin.String) {
           _builder.putMetadata(key, value)
         }
      /**
       * ```
       * Key value map of additional metadata that would be exposed to
       * application developers and could be used for filtering
       * ```
       *
       * `map<string, string> metadata = 2 [json_name = "metadata"];`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("setMetadata")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
        .set(key: kotlin.String, value: kotlin.String) {
           put(key, value)
         }
      /**
       * ```
       * Key value map of additional metadata that would be exposed to
       * application developers and could be used for filtering
       * ```
       *
       * `map<string, string> metadata = 2 [json_name = "metadata"];`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("removeMetadata")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
        .remove(key: kotlin.String) {
           _builder.removeMetadata(key)
         }
      /**
       * ```
       * Key value map of additional metadata that would be exposed to
       * application developers and could be used for filtering
       * ```
       *
       * `map<string, string> metadata = 2 [json_name = "metadata"];`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("putAllMetadata")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
        .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
           _builder.putAllMetadata(map)
         }
      /**
       * ```
       * Key value map of additional metadata that would be exposed to
       * application developers and could be used for filtering
       * ```
       *
       * `map<string, string> metadata = 2 [json_name = "metadata"];`
       */
      @kotlin.jvm.JvmSynthetic
      @JvmName("clearMetadata")
      public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, MetadataProxy>
        .clear() {
           _builder.clearMetadata()
         }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.InvitationV1.copy(block: com.xmtp.message_contents.InvitationV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.InvitationV1 =
  com.xmtp.message_contents.InvitationV1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256.copy(block: com.xmtp.message_contents.InvitationV1Kt.Aes256gcmHkdfsha256Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256 =
  com.xmtp.message_contents.InvitationV1Kt.Aes256gcmHkdfsha256Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.InvitationV1.Context.copy(block: com.xmtp.message_contents.InvitationV1Kt.ContextKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.InvitationV1.Context =
  com.xmtp.message_contents.InvitationV1Kt.ContextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.InvitationV1OrBuilder.contextOrNull: com.xmtp.message_contents.InvitationV1.Context?
  get() = if (hasContext()) getContext() else null

public val com.xmtp.message_contents.InvitationV1OrBuilder.aes256GcmHkdfSha256OrNull: com.xmtp.message_contents.InvitationV1.Aes256gcmHkdfsha256?
  get() = if (hasAes256GcmHkdfSha256()) getAes256GcmHkdfSha256() else null

