// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializemessageHeaderV2")
public inline fun messageHeaderV2(block: com.xmtp.message_contents.MessageHeaderV2Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.MessageHeaderV2 =
  com.xmtp.message_contents.MessageHeaderV2Kt.Dsl._create(com.xmtp.message_contents.MessageHeaderV2.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message header carries information that is not encrypted, and is therefore
 * observable by the network. It is however authenticated as associated data
 * of the AEAD encryption used to protect the message,
 * thus providing tamper evidence.
 * ```
 *
 * Protobuf type `xmtp.message_contents.MessageHeaderV2`
 */
public object MessageHeaderV2Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.MessageHeaderV2.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.MessageHeaderV2.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.MessageHeaderV2 = _builder.build()

    /**
     * <pre>
     * sender specified message creation time
     * </pre>
     *
     * <code>uint64 created_ns = 1 [json_name = "createdNs"];</code>
     */
    public var createdNs: kotlin.Long
      @JvmName("getCreatedNs")
      get() = _builder.getCreatedNs()
      @JvmName("setCreatedNs")
      set(value) {
        _builder.setCreatedNs(value)
      }
    /**
     * ```
     * sender specified message creation time
     * ```
     *
     * `uint64 created_ns = 1 [json_name = "createdNs"];`
     */
    public fun clearCreatedNs() {
      _builder.clearCreatedNs()
    }

    /**
     * ```
     * the topic the message belongs to
     * ```
     *
     * `string topic = 2 [json_name = "topic"];`
     */
    public var topic: kotlin.String
      @JvmName("getTopic")
      get() = _builder.getTopic()
      @JvmName("setTopic")
      set(value) {
        _builder.setTopic(value)
      }
    /**
     * ```
     * the topic the message belongs to
     * ```
     *
     * `string topic = 2 [json_name = "topic"];`
     */
    public fun clearTopic() {
      _builder.clearTopic()
    }
  }
}
public inline fun com.xmtp.message_contents.MessageHeaderV2.copy(block: com.xmtp.message_contents.MessageHeaderV2Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.MessageHeaderV2 =
  com.xmtp.message_contents.MessageHeaderV2Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

