// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/private_key.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializeprivateKey")
public inline fun privateKey(block: com.xmtp.message_contents.PrivateKeyKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.PrivateKey =
  com.xmtp.message_contents.PrivateKeyKt.Dsl._create(com.xmtp.message_contents.PrivateKey.newBuilder()).apply { block() }._build()
/**
 * ```
 * LEGACY: PrivateKey generalized to support different key types
 * ```
 *
 * Protobuf type `xmtp.message_contents.PrivateKey`
 */
public object PrivateKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.PrivateKey.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.PrivateKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.PrivateKey = _builder.build()

    /**
     * ```
     * time the key was created
     * ```
     *
     * `uint64 timestamp = 1 [json_name = "timestamp"];`
     */
    public var timestamp: kotlin.Long
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * ```
     * time the key was created
     * ```
     *
     * `uint64 timestamp = 1 [json_name = "timestamp"];`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * `.xmtp.message_contents.PrivateKey.Secp256k1 secp256k1 = 2 [json_name = "secp256k1"];`
     */
    public var secp256K1: com.xmtp.message_contents.PrivateKey.Secp256k1
      @JvmName("getSecp256K1")
      get() = _builder.getSecp256K1()
      @JvmName("setSecp256K1")
      set(value) {
        _builder.setSecp256K1(value)
      }
    /**
     * `.xmtp.message_contents.PrivateKey.Secp256k1 secp256k1 = 2 [json_name = "secp256k1"];`
     */
    public fun clearSecp256K1() {
      _builder.clearSecp256K1()
    }
    /**
     * `.xmtp.message_contents.PrivateKey.Secp256k1 secp256k1 = 2 [json_name = "secp256k1"];`
     * @return Whether the secp256k1 field is set.
     */
    public fun hasSecp256K1(): kotlin.Boolean {
      return _builder.hasSecp256K1()
    }

    /**
     * ```
     * public key for this private key
     * ```
     *
     * `.xmtp.message_contents.PublicKey public_key = 3 [json_name = "publicKey"];`
     */
    public var publicKey: com.xmtp.message_contents.PublicKey
      @JvmName("getPublicKey")
      get() = _builder.getPublicKey()
      @JvmName("setPublicKey")
      set(value) {
        _builder.setPublicKey(value)
      }
    /**
     * ```
     * public key for this private key
     * ```
     *
     * `.xmtp.message_contents.PublicKey public_key = 3 [json_name = "publicKey"];`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }
    /**
     * ```
     * public key for this private key
     * ```
     *
     * `.xmtp.message_contents.PublicKey public_key = 3 [json_name = "publicKey"];`
     * @return Whether the publicKey field is set.
     */
    public fun hasPublicKey(): kotlin.Boolean {
      return _builder.hasPublicKey()
    }
    public val unionCase: com.xmtp.message_contents.PrivateKey.UnionCase
      @JvmName("getUnionCase")
      get() = _builder.getUnionCase()

    public fun clearUnion() {
      _builder.clearUnion()
    }
  }
  @kotlin.jvm.JvmName("-initializesecp256k1")
  public inline fun secp256k1(block: com.xmtp.message_contents.PrivateKeyKt.Secp256k1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.PrivateKey.Secp256k1 =
    com.xmtp.message_contents.PrivateKeyKt.Secp256k1Kt.Dsl._create(com.xmtp.message_contents.PrivateKey.Secp256k1.newBuilder()).apply { block() }._build()
  /**
   * ```
   * EC: SECP256k1
   * ```
   *
   * Protobuf type `xmtp.message_contents.PrivateKey.Secp256k1`
   */
  public object Secp256k1Kt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.xmtp.message_contents.PrivateKey.Secp256k1.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.xmtp.message_contents.PrivateKey.Secp256k1.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.xmtp.message_contents.PrivateKey.Secp256k1 = _builder.build()

      /**
       * ```
       * D big-endian, 32 bytes
       * ```
       *
       * `bytes bytes = 1 [json_name = "bytes"];`
       */
      public var bytes: com.google.protobuf.ByteString
        @JvmName("getBytes")
        get() = _builder.getBytes()
        @JvmName("setBytes")
        set(value) {
          _builder.setBytes(value)
        }
      /**
       * ```
       * D big-endian, 32 bytes
       * ```
       *
       * `bytes bytes = 1 [json_name = "bytes"];`
       */
      public fun clearBytes() {
        _builder.clearBytes()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.PrivateKey.copy(block: com.xmtp.message_contents.PrivateKeyKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.PrivateKey =
  com.xmtp.message_contents.PrivateKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.PrivateKey.Secp256k1.copy(block: com.xmtp.message_contents.PrivateKeyKt.Secp256k1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.PrivateKey.Secp256k1 =
  com.xmtp.message_contents.PrivateKeyKt.Secp256k1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.PrivateKeyOrBuilder.secp256K1OrNull: com.xmtp.message_contents.PrivateKey.Secp256k1?
  get() = if (hasSecp256K1()) getSecp256K1() else null

public val com.xmtp.message_contents.PrivateKeyOrBuilder.publicKeyOrNull: com.xmtp.message_contents.PublicKey?
  get() = if (hasPublicKey()) getPublicKey() else null

