// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/invitation.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializesealedInvitationV1")
public inline fun sealedInvitationV1(block: com.xmtp.message_contents.SealedInvitationV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.SealedInvitationV1 =
  com.xmtp.message_contents.SealedInvitationV1Kt.Dsl._create(com.xmtp.message_contents.SealedInvitationV1.newBuilder()).apply { block() }._build()
/**
 * ```
 * Sealed Invitation V1
 * Invitation encrypted with key material derived from the sender's and
 * recipient's public key bundles using simplified X3DH where
 * the sender's ephemeral key is replaced with sender's pre-key.
 * ```
 *
 * Protobuf type `xmtp.message_contents.SealedInvitationV1`
 */
public object SealedInvitationV1Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.SealedInvitationV1.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.SealedInvitationV1.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.SealedInvitationV1 = _builder.build()

    /**
     * ```
     * encoded SealedInvitationHeaderV1 used as associated data for Ciphertext
     * ```
     *
     * `bytes header_bytes = 1 [json_name = "headerBytes"];`
     */
    public var headerBytes: com.google.protobuf.ByteString
      @JvmName("getHeaderBytes")
      get() = _builder.getHeaderBytes()
      @JvmName("setHeaderBytes")
      set(value) {
        _builder.setHeaderBytes(value)
      }
    /**
     * ```
     * encoded SealedInvitationHeaderV1 used as associated data for Ciphertext
     * ```
     *
     * `bytes header_bytes = 1 [json_name = "headerBytes"];`
     */
    public fun clearHeaderBytes() {
      _builder.clearHeaderBytes()
    }

    /**
     * ```
     * Ciphertext.payload MUST contain encrypted InvitationV1.
     * ```
     *
     * `.xmtp.message_contents.Ciphertext ciphertext = 2 [json_name = "ciphertext"];`
     */
    public var ciphertext: com.xmtp.message_contents.Ciphertext
      @JvmName("getCiphertext")
      get() = _builder.getCiphertext()
      @JvmName("setCiphertext")
      set(value) {
        _builder.setCiphertext(value)
      }
    /**
     * ```
     * Ciphertext.payload MUST contain encrypted InvitationV1.
     * ```
     *
     * `.xmtp.message_contents.Ciphertext ciphertext = 2 [json_name = "ciphertext"];`
     */
    public fun clearCiphertext() {
      _builder.clearCiphertext()
    }
    /**
     * ```
     * Ciphertext.payload MUST contain encrypted InvitationV1.
     * ```
     *
     * `.xmtp.message_contents.Ciphertext ciphertext = 2 [json_name = "ciphertext"];`
     * @return Whether the ciphertext field is set.
     */
    public fun hasCiphertext(): kotlin.Boolean {
      return _builder.hasCiphertext()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.SealedInvitationV1.copy(block: com.xmtp.message_contents.SealedInvitationV1Kt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.SealedInvitationV1 =
  com.xmtp.message_contents.SealedInvitationV1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.SealedInvitationV1OrBuilder.ciphertextOrNull: com.xmtp.message_contents.Ciphertext?
  get() = if (hasCiphertext()) getCiphertext() else null

