// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/public_key.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializesignedPublicKeyBundle")
public inline fun signedPublicKeyBundle(block: com.xmtp.message_contents.SignedPublicKeyBundleKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.SignedPublicKeyBundle =
  com.xmtp.message_contents.SignedPublicKeyBundleKt.Dsl._create(com.xmtp.message_contents.SignedPublicKeyBundle.newBuilder()).apply { block() }._build()
/**
 * ```
 * PublicKeyBundle packages the cryptographic keys associated with a wallet.
 * ```
 *
 * Protobuf type `xmtp.message_contents.SignedPublicKeyBundle`
 */
public object SignedPublicKeyBundleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.SignedPublicKeyBundle.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.SignedPublicKeyBundle.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.SignedPublicKeyBundle = _builder.build()

    /**
     * ```
     * Identity key MUST be signed by the wallet.
     * ```
     *
     * `.xmtp.message_contents.SignedPublicKey identity_key = 1 [json_name = "identityKey"];`
     */
    public var identityKey: com.xmtp.message_contents.SignedPublicKey
      @JvmName("getIdentityKey")
      get() = _builder.getIdentityKey()
      @JvmName("setIdentityKey")
      set(value) {
        _builder.setIdentityKey(value)
      }
    /**
     * ```
     * Identity key MUST be signed by the wallet.
     * ```
     *
     * `.xmtp.message_contents.SignedPublicKey identity_key = 1 [json_name = "identityKey"];`
     */
    public fun clearIdentityKey() {
      _builder.clearIdentityKey()
    }
    /**
     * ```
     * Identity key MUST be signed by the wallet.
     * ```
     *
     * `.xmtp.message_contents.SignedPublicKey identity_key = 1 [json_name = "identityKey"];`
     * @return Whether the identityKey field is set.
     */
    public fun hasIdentityKey(): kotlin.Boolean {
      return _builder.hasIdentityKey()
    }

    /**
     * ```
     * Pre-key MUST be signed by the identity key.
     * ```
     *
     * `.xmtp.message_contents.SignedPublicKey pre_key = 2 [json_name = "preKey"];`
     */
    public var preKey: com.xmtp.message_contents.SignedPublicKey
      @JvmName("getPreKey")
      get() = _builder.getPreKey()
      @JvmName("setPreKey")
      set(value) {
        _builder.setPreKey(value)
      }
    /**
     * ```
     * Pre-key MUST be signed by the identity key.
     * ```
     *
     * `.xmtp.message_contents.SignedPublicKey pre_key = 2 [json_name = "preKey"];`
     */
    public fun clearPreKey() {
      _builder.clearPreKey()
    }
    /**
     * ```
     * Pre-key MUST be signed by the identity key.
     * ```
     *
     * `.xmtp.message_contents.SignedPublicKey pre_key = 2 [json_name = "preKey"];`
     * @return Whether the preKey field is set.
     */
    public fun hasPreKey(): kotlin.Boolean {
      return _builder.hasPreKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_contents.SignedPublicKeyBundle.copy(block: com.xmtp.message_contents.SignedPublicKeyBundleKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.SignedPublicKeyBundle =
  com.xmtp.message_contents.SignedPublicKeyBundleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.SignedPublicKeyBundleOrBuilder.identityKeyOrNull: com.xmtp.message_contents.SignedPublicKey?
  get() = if (hasIdentityKey()) getIdentityKey() else null

public val com.xmtp.message_contents.SignedPublicKeyBundleOrBuilder.preKeyOrNull: com.xmtp.message_contents.SignedPublicKey?
  get() = if (hasPreKey()) getPreKey() else null

