// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/content.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializesignedContent")
public inline fun signedContent(block: com.xmtp.message_contents.SignedContentKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.SignedContent =
  com.xmtp.message_contents.SignedContentKt.Dsl._create(com.xmtp.message_contents.SignedContent.newBuilder()).apply { block() }._build()
/**
 * ```
 * SignedContent attaches a signature to EncodedContent.
 * ```
 *
 * Protobuf type `xmtp.message_contents.SignedContent`
 */
public object SignedContentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.SignedContent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.SignedContent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.SignedContent = _builder.build()

    /**
     * <pre>
     * MUST contain EncodedContent
     * </pre>
     *
     * <code>bytes payload = 1 [json_name = "payload"];</code>
     */
    public var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.getPayload()
      @JvmName("setPayload")
      set(value) {
        _builder.setPayload(value)
      }
    /**
     * ```
     * MUST contain EncodedContent
     * ```
     *
     * `bytes payload = 1 [json_name = "payload"];`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `.xmtp.message_contents.SignedPublicKeyBundle sender = 2 [json_name = "sender"];`
     */
    public var sender: com.xmtp.message_contents.SignedPublicKeyBundle
      @JvmName("getSender")
      get() = _builder.getSender()
      @JvmName("setSender")
      set(value) {
        _builder.setSender(value)
      }
    /**
     * `.xmtp.message_contents.SignedPublicKeyBundle sender = 2 [json_name = "sender"];`
     */
    public fun clearSender() {
      _builder.clearSender()
    }
    /**
     * `.xmtp.message_contents.SignedPublicKeyBundle sender = 2 [json_name = "sender"];`
     * @return Whether the sender field is set.
     */
    public fun hasSender(): kotlin.Boolean {
      return _builder.hasSender()
    }

    /**
     * ```
     * MUST be a signature of a concatenation of
     * the message header bytes and the payload bytes,
     * signed by the sender's pre-key.
     * ```
     *
     * `.xmtp.message_contents.Signature signature = 3 [json_name = "signature"];`
     */
    public var signature: com.xmtp.message_contents.Signature
      @JvmName("getSignature")
      get() = _builder.getSignature()
      @JvmName("setSignature")
      set(value) {
        _builder.setSignature(value)
      }
    /**
     * ```
     * MUST be a signature of a concatenation of
     * the message header bytes and the payload bytes,
     * signed by the sender's pre-key.
     * ```
     *
     * `.xmtp.message_contents.Signature signature = 3 [json_name = "signature"];`
     */
    public fun clearSignature() {
      _builder.clearSignature()
    }
    /**
     * ```
     * MUST be a signature of a concatenation of
     * the message header bytes and the payload bytes,
     * signed by the sender's pre-key.
     * ```
     *
     * `.xmtp.message_contents.Signature signature = 3 [json_name = "signature"];`
     * @return Whether the signature field is set.
     */
    public fun hasSignature(): kotlin.Boolean {
      return _builder.hasSignature()
    }
  }
}
public inline fun com.xmtp.message_contents.SignedContent.copy(block: com.xmtp.message_contents.SignedContentKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.SignedContent =
  com.xmtp.message_contents.SignedContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.SignedContentOrBuilder.senderOrNull: com.xmtp.message_contents.SignedPublicKeyBundle?
  get() = if (hasSender()) getSender() else null

public val com.xmtp.message_contents.SignedContentOrBuilder.signatureOrNull: com.xmtp.message_contents.Signature?
  get() = if (hasSignature()) getSignature() else null

