// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_contents/public_key.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_contents;

@kotlin.jvm.JvmName("-initializeunsignedPublicKey")
public inline fun unsignedPublicKey(block: com.xmtp.message_contents.UnsignedPublicKeyKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.UnsignedPublicKey =
  com.xmtp.message_contents.UnsignedPublicKeyKt.Dsl._create(com.xmtp.message_contents.UnsignedPublicKey.newBuilder()).apply { block() }._build()
/**
 * ```
 * UnsignedPublicKey represents a generalized public key,
 * defined as a union to support cryptographic algorithm agility.
 * ```
 *
 * Protobuf type `xmtp.message_contents.UnsignedPublicKey`
 */
public object UnsignedPublicKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_contents.UnsignedPublicKey.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_contents.UnsignedPublicKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_contents.UnsignedPublicKey = _builder.build()

    /**
     * <code>uint64 created_ns = 1 [json_name = "createdNs"];</code>
     */
    public var createdNs: kotlin.Long
      @JvmName("getCreatedNs")
      get() = _builder.getCreatedNs()
      @JvmName("setCreatedNs")
      set(value) {
        _builder.setCreatedNs(value)
      }
    /**
     * `uint64 created_ns = 1 [json_name = "createdNs"];`
     */
    public fun clearCreatedNs() {
      _builder.clearCreatedNs()
    }

    /**
     * `.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed secp256k1_uncompressed = 3 [json_name = "secp256k1Uncompressed"];`
     */
    public var secp256K1Uncompressed: com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed
      @JvmName("getSecp256K1Uncompressed")
      get() = _builder.getSecp256K1Uncompressed()
      @JvmName("setSecp256K1Uncompressed")
      set(value) {
        _builder.setSecp256K1Uncompressed(value)
      }
    /**
     * `.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed secp256k1_uncompressed = 3 [json_name = "secp256k1Uncompressed"];`
     */
    public fun clearSecp256K1Uncompressed() {
      _builder.clearSecp256K1Uncompressed()
    }
    /**
     * `.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed secp256k1_uncompressed = 3 [json_name = "secp256k1Uncompressed"];`
     * @return Whether the secp256k1Uncompressed field is set.
     */
    public fun hasSecp256K1Uncompressed(): kotlin.Boolean {
      return _builder.hasSecp256K1Uncompressed()
    }
    public val unionCase: com.xmtp.message_contents.UnsignedPublicKey.UnionCase
      @JvmName("getUnionCase")
      get() = _builder.getUnionCase()

    public fun clearUnion() {
      _builder.clearUnion()
    }
  }
  @kotlin.jvm.JvmName("-initializesecp256k1Uncompressed")
  public inline fun secp256k1Uncompressed(block: com.xmtp.message_contents.UnsignedPublicKeyKt.Secp256k1UncompressedKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed =
    com.xmtp.message_contents.UnsignedPublicKeyKt.Secp256k1UncompressedKt.Dsl._create(com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed.newBuilder()).apply { block() }._build()
  /**
   * ```
   * EC: SECP256k1
   * ```
   *
   * Protobuf type `xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed`
   */
  public object Secp256k1UncompressedKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed = _builder.build()

      /**
       * <pre>
       * uncompressed point with prefix (0x04) [ P || X || Y ], 65 bytes
       * </pre>
       *
       * <code>bytes bytes = 1 [json_name = "bytes"];</code>
       */
      public var bytes: com.google.protobuf.ByteString
        @JvmName("getBytes")
        get() = _builder.getBytes()
        @JvmName("setBytes")
        set(value) {
          _builder.setBytes(value)
        }
      /**
       * ```
       * uncompressed point with prefix (0x04) [ P || X || Y ], 65 bytes
       * ```
       *
       * `bytes bytes = 1 [json_name = "bytes"];`
       */
      public fun clearBytes() {
        _builder.clearBytes()
      }
    }
  }
}
public inline fun com.xmtp.message_contents.UnsignedPublicKey.copy(block: com.xmtp.message_contents.UnsignedPublicKeyKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.UnsignedPublicKey =
  com.xmtp.message_contents.UnsignedPublicKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public inline fun com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed.copy(block: com.xmtp.message_contents.UnsignedPublicKeyKt.Secp256k1UncompressedKt.Dsl.() -> kotlin.Unit): com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed =
  com.xmtp.message_contents.UnsignedPublicKeyKt.Secp256k1UncompressedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_contents.UnsignedPublicKeyOrBuilder.secp256K1UncompressedOrNull: com.xmtp.message_contents.UnsignedPublicKey.Secp256k1Uncompressed?
  get() = if (hasSecp256K1Uncompressed()) getSecp256K1Uncompressed() else null

