// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/authn.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializeauthData")
public inline fun authData(block: com.xmtp.message_api.v1.AuthDataKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.AuthData =
  com.xmtp.message_api.v1.AuthDataKt.Dsl._create(com.xmtp.message_api.v1.AuthData.newBuilder()).apply { block() }._build()
/**
 * ```
 * AuthData carries token parameters that are authenticated
 * by the identity key signature.
 * It is embedded in the Token structure as bytes
 * so that the bytes don't need to be reconstructed
 * to verify the token signature.
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.AuthData`
 */
public object AuthDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.AuthData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.AuthData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.AuthData = _builder.build()

    /**
     * ```
     * address of the wallet
     * ```
     *
     * `string wallet_addr = 1 [json_name = "walletAddr"];`
     */
    public var walletAddr: kotlin.String
      @JvmName("getWalletAddr")
      get() = _builder.getWalletAddr()
      @JvmName("setWalletAddr")
      set(value) {
        _builder.setWalletAddr(value)
      }
    /**
     * ```
     * address of the wallet
     * ```
     *
     * `string wallet_addr = 1 [json_name = "walletAddr"];`
     */
    public fun clearWalletAddr() {
      _builder.clearWalletAddr()
    }

    /**
     * <pre>
     * time when the token was generated/signed 
     * </pre>
     *
     * <code>uint64 created_ns = 2 [json_name = "createdNs"];</code>
     */
    public var createdNs: kotlin.Long
      @JvmName("getCreatedNs")
      get() = _builder.getCreatedNs()
      @JvmName("setCreatedNs")
      set(value) {
        _builder.setCreatedNs(value)
      }
    /**
     * ```
     * time when the token was generated/signed 
     * ```
     *
     * `uint64 created_ns = 2 [json_name = "createdNs"];`
     */
    public fun clearCreatedNs() {
      _builder.clearCreatedNs()
    }
  }
}
public inline fun com.xmtp.message_api.v1.AuthData.copy(block: com.xmtp.message_api.v1.AuthDataKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.AuthData =
  com.xmtp.message_api.v1.AuthDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

