// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializebatchQueryRequest")
public inline fun batchQueryRequest(block: com.xmtp.message_api.v1.BatchQueryRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.BatchQueryRequest =
  com.xmtp.message_api.v1.BatchQueryRequestKt.Dsl._create(com.xmtp.message_api.v1.BatchQueryRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * BatchQuery
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.BatchQueryRequest`
 */
public object BatchQueryRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.BatchQueryRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.BatchQueryRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.BatchQueryRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RequestsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     */
     public val requests: com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRequestsList()
      )
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     * @param value The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>.add(value: com.xmtp.message_api.v1.QueryRequest) {
      _builder.addRequests(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     * @param value The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRequests")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>.plusAssign(value: com.xmtp.message_api.v1.QueryRequest) {
      add(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     * @param values The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>.addAll(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.QueryRequest>) {
      _builder.addAllRequests(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     * @param values The requests to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRequests")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>.plusAssign(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.QueryRequest>) {
      addAll(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     * @param index The index to set the value at.
     * @param value The requests to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRequests")
    public operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>.set(index: kotlin.Int, value: com.xmtp.message_api.v1.QueryRequest) {
      _builder.setRequests(index, value)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryRequest requests = 1 [json_name = "requests"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRequests")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryRequest, RequestsProxy>.clear() {
      _builder.clearRequests()
    }
  }
}
public inline fun com.xmtp.message_api.v1.BatchQueryRequest.copy(block: com.xmtp.message_api.v1.BatchQueryRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.BatchQueryRequest =
  com.xmtp.message_api.v1.BatchQueryRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

