// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializebatchQueryResponse")
public inline fun batchQueryResponse(block: com.xmtp.message_api.v1.BatchQueryResponseKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.BatchQueryResponse =
  com.xmtp.message_api.v1.BatchQueryResponseKt.Dsl._create(com.xmtp.message_api.v1.BatchQueryResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Response containing a list of QueryResponse messages
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.BatchQueryResponse`
 */
public object BatchQueryResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.BatchQueryResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.BatchQueryResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.BatchQueryResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ResponsesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     */
     public val responses: com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getResponsesList()
      )
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     * @param value The responses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addResponses")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>.add(value: com.xmtp.message_api.v1.QueryResponse) {
      _builder.addResponses(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     * @param value The responses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignResponses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>.plusAssign(value: com.xmtp.message_api.v1.QueryResponse) {
      add(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     * @param values The responses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllResponses")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>.addAll(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.QueryResponse>) {
      _builder.addAllResponses(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     * @param values The responses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllResponses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>.plusAssign(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.QueryResponse>) {
      addAll(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     * @param index The index to set the value at.
     * @param value The responses to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setResponses")
    public operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>.set(index: kotlin.Int, value: com.xmtp.message_api.v1.QueryResponse) {
      _builder.setResponses(index, value)
    }
    /**
     * `repeated .xmtp.message_api.v1.QueryResponse responses = 1 [json_name = "responses"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearResponses")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.QueryResponse, ResponsesProxy>.clear() {
      _builder.clearResponses()
    }
  }
}
public inline fun com.xmtp.message_api.v1.BatchQueryResponse.copy(block: com.xmtp.message_api.v1.BatchQueryResponseKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.BatchQueryResponse =
  com.xmtp.message_api.v1.BatchQueryResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

