// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializeindexCursor")
public inline fun indexCursor(block: com.xmtp.message_api.v1.IndexCursorKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.IndexCursor =
  com.xmtp.message_api.v1.IndexCursorKt.Dsl._create(com.xmtp.message_api.v1.IndexCursor.newBuilder()).apply { block() }._build()
/**
 * ```
 * This is based off of the go-waku Index type, but with the
 * receiverTime and pubsubTopic removed for simplicity.
 * Both removed fields are optional
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.IndexCursor`
 */
public object IndexCursorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.IndexCursor.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.IndexCursor.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.IndexCursor = _builder.build()

    /**
     * <code>bytes digest = 1 [json_name = "digest"];</code>
     */
    public var digest: com.google.protobuf.ByteString
      @JvmName("getDigest")
      get() = _builder.getDigest()
      @JvmName("setDigest")
      set(value) {
        _builder.setDigest(value)
      }
    /**
     * `bytes digest = 1 [json_name = "digest"];`
     */
    public fun clearDigest() {
      _builder.clearDigest()
    }

    /**
     * <code>uint64 sender_time_ns = 2 [json_name = "senderTimeNs"];</code>
     */
    public var senderTimeNs: kotlin.Long
      @JvmName("getSenderTimeNs")
      get() = _builder.getSenderTimeNs()
      @JvmName("setSenderTimeNs")
      set(value) {
        _builder.setSenderTimeNs(value)
      }
    /**
     * `uint64 sender_time_ns = 2 [json_name = "senderTimeNs"];`
     */
    public fun clearSenderTimeNs() {
      _builder.clearSenderTimeNs()
    }
  }
}
public inline fun com.xmtp.message_api.v1.IndexCursor.copy(block: com.xmtp.message_api.v1.IndexCursorKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.IndexCursor =
  com.xmtp.message_api.v1.IndexCursorKt.Dsl._create(this.toBuilder()).apply { block() }._build()

