// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializepublishResponse")
public inline fun publishResponse(block: com.xmtp.message_api.v1.PublishResponseKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.PublishResponse =
  com.xmtp.message_api.v1.PublishResponseKt.Dsl._create(com.xmtp.message_api.v1.PublishResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Empty message as a response for Publish
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.PublishResponse`
 */
public object PublishResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.PublishResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.PublishResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.PublishResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_api.v1.PublishResponse.copy(block: com.xmtp.message_api.v1.PublishResponseKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.PublishResponse =
  com.xmtp.message_api.v1.PublishResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

