// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializepublishRequest")
public inline fun publishRequest(block: com.xmtp.message_api.v1.PublishRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.PublishRequest =
  com.xmtp.message_api.v1.PublishRequestKt.Dsl._create(com.xmtp.message_api.v1.PublishRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Publish
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.PublishRequest`
 */
public object PublishRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.PublishRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.PublishRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.PublishRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnvelopesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     */
     public val envelopes: com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEnvelopesList()
      )
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param value The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.add(value: com.xmtp.message_api.v1.Envelope) {
      _builder.addEnvelopes(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param value The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEnvelopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.plusAssign(value: com.xmtp.message_api.v1.Envelope) {
      add(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param values The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.addAll(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.Envelope>) {
      _builder.addAllEnvelopes(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param values The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEnvelopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.plusAssign(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.Envelope>) {
      addAll(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param index The index to set the value at.
     * @param value The envelopes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEnvelopes")
    public operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.set(index: kotlin.Int, value: com.xmtp.message_api.v1.Envelope) {
      _builder.setEnvelopes(index, value)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.clear() {
      _builder.clearEnvelopes()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_api.v1.PublishRequest.copy(block: com.xmtp.message_api.v1.PublishRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.PublishRequest =
  com.xmtp.message_api.v1.PublishRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

