// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializequeryResponse")
public inline fun queryResponse(block: com.xmtp.message_api.v1.QueryResponseKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.QueryResponse =
  com.xmtp.message_api.v1.QueryResponseKt.Dsl._create(com.xmtp.message_api.v1.QueryResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * The response, containing envelopes, for a query
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.QueryResponse`
 */
public object QueryResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.QueryResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.QueryResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.QueryResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnvelopesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     */
     public val envelopes: com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEnvelopesList()
      )
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param value The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.add(value: com.xmtp.message_api.v1.Envelope) {
      _builder.addEnvelopes(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param value The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEnvelopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.plusAssign(value: com.xmtp.message_api.v1.Envelope) {
      add(value)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param values The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.addAll(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.Envelope>) {
      _builder.addAllEnvelopes(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param values The envelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEnvelopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.plusAssign(values: kotlin.collections.Iterable<com.xmtp.message_api.v1.Envelope>) {
      addAll(values)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     * @param index The index to set the value at.
     * @param value The envelopes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEnvelopes")
    public operator fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.set(index: kotlin.Int, value: com.xmtp.message_api.v1.Envelope) {
      _builder.setEnvelopes(index, value)
    }
    /**
     * `repeated .xmtp.message_api.v1.Envelope envelopes = 1 [json_name = "envelopes"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.xmtp.message_api.v1.Envelope, EnvelopesProxy>.clear() {
      _builder.clearEnvelopes()
    }

    /**
     * `.xmtp.message_api.v1.PagingInfo paging_info = 2 [json_name = "pagingInfo"];`
     */
    public var pagingInfo: com.xmtp.message_api.v1.PagingInfo
      @JvmName("getPagingInfo")
      get() = _builder.getPagingInfo()
      @JvmName("setPagingInfo")
      set(value) {
        _builder.setPagingInfo(value)
      }
    /**
     * `.xmtp.message_api.v1.PagingInfo paging_info = 2 [json_name = "pagingInfo"];`
     */
    public fun clearPagingInfo() {
      _builder.clearPagingInfo()
    }
    /**
     * `.xmtp.message_api.v1.PagingInfo paging_info = 2 [json_name = "pagingInfo"];`
     * @return Whether the pagingInfo field is set.
     */
    public fun hasPagingInfo(): kotlin.Boolean {
      return _builder.hasPagingInfo()
    }
  }
}
public inline fun com.xmtp.message_api.v1.QueryResponse.copy(block: com.xmtp.message_api.v1.QueryResponseKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.QueryResponse =
  com.xmtp.message_api.v1.QueryResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.xmtp.message_api.v1.QueryResponseOrBuilder.pagingInfoOrNull: com.xmtp.message_api.v1.PagingInfo?
  get() = if (hasPagingInfo()) getPagingInfo() else null

