// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializesubscribeRequest")
public inline fun subscribeRequest(block: com.xmtp.message_api.v1.SubscribeRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.SubscribeRequest =
  com.xmtp.message_api.v1.SubscribeRequestKt.Dsl._create(com.xmtp.message_api.v1.SubscribeRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Subscribe
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.SubscribeRequest`
 */
public object SubscribeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.SubscribeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.SubscribeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.SubscribeRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContentTopicsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     * @return A list containing the contentTopics.
     */
    public val contentTopics: com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getContentTopicsList()
      )
    /**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     * @param value The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addContentTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.add(value: kotlin.String) {
      _builder.addContentTopics(value)
    }
    /**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     * @param value The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignContentTopics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     * @param values The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllContentTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllContentTopics(values)
    }
    /**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     * @param values The contentTopics to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllContentTopics")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     * @param index The index to set the value at.
     * @param value The contentTopics to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setContentTopics")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setContentTopics(index, value)
    }/**
     * `repeated string content_topics = 1 [json_name = "contentTopics"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearContentTopics")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ContentTopicsProxy>.clear() {
      _builder.clearContentTopics()
    }}
}
public inline fun com.xmtp.message_api.v1.SubscribeRequest.copy(block: com.xmtp.message_api.v1.SubscribeRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.SubscribeRequest =
  com.xmtp.message_api.v1.SubscribeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

