// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: message_api/v1/message_api.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.xmtp.message_api.v1;

@kotlin.jvm.JvmName("-initializesubscribeAllRequest")
public inline fun subscribeAllRequest(block: com.xmtp.message_api.v1.SubscribeAllRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.SubscribeAllRequest =
  com.xmtp.message_api.v1.SubscribeAllRequestKt.Dsl._create(com.xmtp.message_api.v1.SubscribeAllRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * SubscribeAll
 * ```
 *
 * Protobuf type `xmtp.message_api.v1.SubscribeAllRequest`
 */
public object SubscribeAllRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.xmtp.message_api.v1.SubscribeAllRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.xmtp.message_api.v1.SubscribeAllRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.xmtp.message_api.v1.SubscribeAllRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.xmtp.message_api.v1.SubscribeAllRequest.copy(block: com.xmtp.message_api.v1.SubscribeAllRequestKt.Dsl.() -> kotlin.Unit): com.xmtp.message_api.v1.SubscribeAllRequest =
  com.xmtp.message_api.v1.SubscribeAllRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

