name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  library:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Dry run version bump and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          custom_tag: 3.0.1
      - name: Log dry run output
        run: |
          echo "Simulated tag: ${{ steps.tag_version.outputs.new_tag }}"
          echo "Simulated version: ${{ steps.tag_version.outputs.new_version }}"
