name: Release XMTP Android Package
on:
  push:
    branches:
      - xmtp-legacy

jobs:
  library:
    name: Release Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Tag version 0.16.4
        run: |
          git tag 0.16.4
          git push origin 0.16.4

      - name: Create a GitHub release for version 0.16.4
        uses: ncipollo/release-action@v1
        with:
          tag: "0.16.4"
          name: "Release 0.16.4"
          body: "Patch release for inboxId and group fixes 0.16.4"

      - name: Gradle Publish
        env:
          RELEASE_VERSION: "0.16.4"
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGN_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          SIGN_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          MAVEN_PROFILE_ID: ${{ secrets.MAVEN_PROFILE_ID }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository