name: Release XMTP Android Package
on:
  push:
    branches:
      - release

jobs:
  library:
    name: Release Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Set Tag
        run: |
          TAG=`echo $(git describe --tags --abbrev=0)`
          echo "GIT_TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Gradle Publish
        env:
          RELEASE_VERSION: ${{ env.GIT_TAG }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: ./gradlew publish
