name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library:
    name: Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Update Homebrew and save docker version
        run: |
          brew update --preinstall
          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/docker.rb" > .github/brew-formulae
      - name: Configure Homebrew docker cache files
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/docker--*
            ~/Library/Caches/Homebrew/downloads/*--docker-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install Docker and start colima
        id: install_mac_docker
        run: |
          brew install docker docker-compose
          # Docker engine is no longer available because of licensing
          # Alternative Colima is part of the github macOS runner
          colima start
          # Ensure colima is configured for later user
          echo "DOCKER_HOST=unix://$HOME/.colima/default/docker.sock" >> $GITHUB_ENV
          # Verify Docker
          docker ps
      - name: Gradle Run Unit Tests
        run: ./gradlew library:testDebug
      - name: Start local test server
        run: docker-compose -p xmtp -f dev/local/docker-compose.yml up -d
      - name: Gradle Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: Stop local test server
        run: docker-compose -p xmtp -f dev/local/docker-compose.yml down

