name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library-unit:
    name: Library (Unit Tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Start Docker containers
        run: dev/up
      - name: Gradle Run Unit Tests
        run: ./gradlew test
  library-integration:
    name: Library (Integration Tests)
    runs-on: warp-macos-13-arm64-6x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Start Docker containers
        run: dev/up
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
