name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library-integration:
    name: Library (Integration Tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Start Docker containers
        run: dev/up
      - name: Restart ADB Server
        run: |
          adb kill-server || true
          adb start-server
          adb devices
      - name: Gradle Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          ram-size: 4096M
          disk-size: 8000M
          disable-animations: true
          emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -verbose"
          boot-timeout: 600
          script: |
            echo "Waiting for emulator..."
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
            adb shell input keyevent 82
            ./gradlew connectedCheck
  