name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library-unit:
    name: Library (Unit Tests)
    runs-on: warp-ubuntu-latest-x64-16x
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Start Docker containers
        run: dev/up
      - name: Gradle Run Unit Tests
        run: ./gradlew library:testDebug
  library-integration:
    name: Library (Integration Tests)
    runs-on: warp-macos-latest-arm64-6x
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Docker
        run: brew install docker docker-compose
      - name: Start Colima
        run: colima start
      - name: Start Docker containers
        run: dev/up
      - name: Gradle Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

