name: Android XMTP Tests
on:
  push:
    branches:
      - main
jobs:
  library:
    name: Test (Library)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Gradle Run Tests
        run: ./gradlew library:testDebug
