name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library-integration:
    name: Library (Integration Tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Start Docker containers
        run: ./dev/up

      - name: Wait for Services
        run: sleep 5s  # Give DB and Node services time to start

      - name: Verify Running Containers
        run: docker ps  # Debugging: Ensure required services are running

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Create AVD
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: true
          emulator-options: "-no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none -no-snapshot-load -no-snapshot-save"
          disable-animations: true
          script: echo "AVD ready for use."

      - name: Restart ADB Server
        run: |
          adb kill-server || true
          adb start-server
          adb devices
          adb reconnect

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          echo "Waiting for emulator to come online..."
          timeout=300
          while [[ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" != "1" && "$timeout" -gt 0 ]]; do
            sleep 5
            timeout=$((timeout - 5))
            echo "Waiting... ($timeout seconds left)"
            adb shell getprop sys.boot_completed
          done
          if [[ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" != "1" ]]; then
            echo "Emulator failed to boot!"
            exit 1
          fi
          echo "Emulator is fully booted!"
          adb shell input keyevent 82

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: "-no-snapshot-save -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim -camera-back none"
          disable-animations: true
          script: ./gradlew connectedCheck
