name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library-unit:
    name: Library (Unit Tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Start local test server
        run: docker-compose -p xmtp -f dev/local/docker-compose.yml up -d
      - name: Gradle Run Unit Tests
        run: ./gradlew library:testDebug
      - name: Stop local test server
        run: docker-compose -p xmtp -f dev/local/docker-compose.yml down
  library-integration:
    name: Library (Integration Tests)
    runs-on: macos-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        # Workaround for https://github.com/actions/runner-images/issues/8104
      - name: Fix Qemu Error
        run: |
          brew remove --ignore-dependencies qemu
          curl -o ./qemu.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/f88e30b3a23ef3735580f9b05535ce5a0a03c9e3/Formula/qemu.rb
          brew install ./qemu.rb
      - name: Set up Docker
        run: brew install docker docker-compose
      - name: Start Colima
        run: colima start
      - name: Start local test server
        run: docker-compose -p xmtp -f dev/local/docker-compose.yml up -d
      - name: Gradle Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: Stop local test server
        run: docker-compose -p xmtp -f dev/local/docker-compose.yml down

