name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GPR_USER: ${{ secrets.GITHUB_ACTOR }}

jobs:
  library-integration:
    name: Library (Integration Tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Start Docker containers
        run: ./dev/up

      - name: Wait for Services
        run: sleep 5s  # Give DB and Node services time to start

      - name: Verify Running Containers
        run: docker ps  # Debugging: Ensure required services are running

      - name: Gradle Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24  # Use stable API level from the example workflow
          arch: x86_64
          target: google_apis
          ram-size: 4096M
          disk-size: 8000M
          disable-animations: true
          emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -verbose"
          emulator-boot-timeout: 600
          script: |
            echo "Waiting for emulator to boot..."
            adb wait-for-device
            boot_completed=""
            while [[ -z "$boot_completed" ]]; do
              sleep 5
              boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
              echo "Boot status: $boot_completed"
            done
            echo "Emulator is fully booted!"
            adb shell input keyevent 82
            ./gradlew connectedCheck
